ignore:
  - 'Mini Model <minimodel@metamodel.me>'

exclude:
  - /^src\/Resources\/contao\/languages/

mapping:
  'Andreas Isaak <info@andreas-isaak.de>': 'Andreas Isaak <andy.jared@googlemail.com>'
  'Christopher Boelter <christopher@boelter.eu>':
    - 'cogizz <c.boelter@cogizz.de>'
    - 'cboelter <christopher@boelter.eu>'
    - 'Christopher Boelter <c.boelter@cogizz.de>'
  'Ingolf Steinhardt <info@e-spin.de>':
    - 'zonky2 <info@e-spin.de>'
    - 'Ingolf Steinhardt <info@e-spin.de>'
    - 'Ingolf Steinhardt <git@e-spin.de>'
