services:
    MetaModels\AttributeFileBundle\EventListener\BuildFrontendUploadListener:
        public: false
        calls:
            -   method: setScopeDeterminator
                arguments:
                    - '@cca.dc-general.scope-matcher'
        arguments:
            - '@metamodels.view_combination'
            - '@security.token_storage'
            - '@contao.insert_tag.parser'
        tags:
            -   name: kernel.event_listener
                event: metamodels.dc-general.events.metamodel.build.attribute
                priority: -128
