services:
  metamodels.attribute_file.event_listener.image_size_options:
    class: MetaModels\AttributeFileBundle\EventListener\ImageSizeOptionsProvider
    arguments:
      $imageSizes: '@contao.image.sizes'
      $translator: '@translator'

  metamodels.attribute_file.event_listener.remove_type_options:
    class: MetaModels\AttributeFileBundle\EventListener\DcGeneral\Table\Attribute\RemoveTypeOptions
    public: true
    tags:
      - name: kernel.event_listener
        event: dc-general.view.contao2backend.get-property-options
        method: removeOption
        priority: -1

  metamodels.attribute_file.event_listener.remove_attid_options:
    class: MetaModels\AttributeFileBundle\EventListener\DcGeneral\Table\FilterSetting\RemoveAttIdOptions
    public: true
    tags:
      - name: kernel.event_listener
        event: dc-general.view.contao2backend.get-property-options
        method: removeOption
        priority: -1

  metamodels.attribute_file.event_listener.build_attribute:
    class: MetaModels\AttributeFileBundle\EventListener\BuildAttributeListener
    public: true
    tags:
      - name: kernel.event_listener
        event: metamodels.dc-general.events.metamodel.build.attribute
        method: buildAttribute

  metamodels.attribute_file.event_listener.build-data-definition:
    class: MetaModels\AttributeFileBundle\EventListener\BuildDataDefinitionListener
    public: true
    tags:
      - name: kernel.event_listener
        event: dc-general.factory.build-data-definition
        method: buildDataDefinition
        priority: 0

  MetaModels\AttributeFileBundle\EventListener\DcGeneral\Table\DcaSetting\FileWidgetModeOptions:
    public: false
    arguments:
      $scopeDeterminator: '@cca.dc-general.scope-matcher'
      $factory: '@MetaModels\IFactory'
      $connection: '@database_connection'
      # The $frontendEditing argument where set in the extension.
      $frontendEditing: ~
    tags:
      - name: kernel.event_listener
        event: dc-general.view.contao2backend.get-property-options

  MetaModels\AttributeFileBundle\EventListener\DcGeneral\Table\DcaSetting\FeeFileImageSizeOptions:
    public: false
    arguments:
      $scopeDeterminator: '@cca.dc-general.scope-matcher'
      $factory: '@MetaModels\IFactory'
      $connection: '@database_connection'
      $optionsProvider: '@metamodels.attribute_file.event_listener.image_size_options'
    tags:
      - name: kernel.event_listener
        event: dc-general.view.contao2backend.get-property-options

  MetaModels\AttributeFileBundle\EventListener\DcGeneral\Table\RenderSetting\FileImageSizeOptions:
    public: false
    arguments:
      $scopeDeterminator: '@cca.dc-general.scope-matcher'
      $factory: '@MetaModels\IFactory'
      $connection: '@database_connection'
      $optionsProvider: '@metamodels.attribute_file.event_listener.image_size_options'
    tags:
      - name: kernel.event_listener
        event: dc-general.view.contao2backend.get-property-options

  MetaModels\AttributeFileBundle\Schema\DoctrineSchemaGenerator:
    tags:
      - { name: 'metamodels.schema-generator.doctrine' }
