services:
    metamodels.attribute_file.toolbox.file:
        class: MetaModels\Helper\ToolboxFile
        public: true
        arguments:
            - "@contao.image.image_factory"
            - "%kernel.project_dir%"

    metamodels.attribute_file.cache_system:
        class: Doctrine\Common\Cache\FilesystemCache
        public: false
        arguments:
            - "%metamodels.attribute_file.cache_dir%"

    metamodels.attribute_file.cache:
        class: Cache\Adapter\Doctrine\DoctrineCachePool
        public: false
        arguments:
            - "@metamodels.attribute_file.cache_system"
