services:
    metamodels.attribute_file.toolbox.file:
        deprecated:
            package: metamodels /attribute_file
            version: 2.1
            message: 'The "%alias_id%" service is deprecated. Use the "@MetaModels\Helper\ToolboxFile".'
        alias: MetaModels\Helper\ToolboxFile
        public: true

    metamodels.attribute_file.cache_system:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        public: false
        arguments:
            - "%metamodels.attribute_file.cache_dir%"

    metamodels.attribute_file.cache:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        public: false
        arguments:
            - "@metamodels.attribute_file.cache_system"

    MetaModels\AttributeFileBundle\Migration\AddSortFieldMigration:
      arguments:
        - '@database_connection'
        - '@metamodels.table_manipulator'
      tags:
        - name: contao.migration

    MetaModels\AttributeFileBundle\Migration\AddProtectedDownloadMigration:
      arguments:
        - '@database_connection'
        - '@metamodels.table_manipulator'
      tags:
        - name: contao.migration

#    MetaModels\AttributeFileBundle\FileUsage\FileUsageProvider:
#      public: true
#      arguments:
#        $factory: '@metamodels.factory'
#        $urlGenerator: '@router'
#        $requestStack: '@request_stack'
#        $csrfTokenManager: '@contao.csrf.token_manager'
#        $csrfTokenName: '%contao.csrf_token_name%'
#      tags:
#        - { name: contao_file_usage.provider }
